version: "3"
services:
  express:
    build: .
    image: node
    container_name: node
    tty: true
    volumes:
      - .:/src
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
